### ISSUE TITLE
Add .env.example

### ISSUE THREAD

**Issue by iyoolaoyabiyi** [Githubstreak/Githubstreak-frontend#17]
### Issue
The project currently lacks a `.env.example` file in both the backend and frontend repositories. This file is crucial for providing contributors with a template of required environment variables, making it easier for them to set up the project locally.

### Impact
1. **Setup Difficulty**: New contributors may struggle to identify the required environment variables, leading to a frustrating setup experience.
2. **Contribution Barrier**: The absence of a `.env.example` file can deter potential contributors who might abandon the effort due to unclear setup instructions.
3. **Consistency**: Having a `.env.example` ensures consistency in the development environment across different machines and contributors.

### Recommended Solution
1. **Create `.env.example`**: Add a `.env.example` file in both the backend and frontend repositories. List all the required environment variables with placeholder values.

#### Backend `.env.example`

```plaintext
PORT=3001
DB_URI=database_url
CLERK_SECRET_KEY=client_key
```

#### Frontend `.env.example`

```plaintext
VITE_CLERK_PUBLISHABLE_KEY=publishable_key
```

### Additional Notes
Including a `.env.example` file will streamline the setup process, making it easier for new developers to contribute to the project. This small addition can significantly improve the developer experience and foster a more inclusive and collaborative environment.

---

**Comment by KwameTech1** [comment]
I have added the example .env file to enhance the developer experience. 

Thank you for pointing out those issues.
