### ISSUE TITLE
[FEATURE] Introduce a new feature that generates memes comparing two GitHub users based on their contribution and also show the graph.

### ISSUE THREAD

**Issue by Agastya18** [Githubstreak/Githubstreak-frontend#24]
**Details:**

*User Input:* Users will be able to input two GitHub usernames.
*Contribution Data:* The system will fetch the contribution for both users.
*Meme Templates:* Select from a range of pre-designed meme templates(or may be ai based) that humorously compare the users’ contributions. 

*Use Case:*
This feature adds a playful element to the GitHub Streak Compare tool, allowing users to engage with their data in a fun, lighthearted way. It’s perfect for friendly rivalries, motivating contributions, and sharing on social platforms.

**Comment by KwameTech1** [comment]
I love this idea.

will you be working on that?

**Comment by Agastya18** [comment]
ya sure , it would be better if we could discuss it first.

**Comment by KwameTech1** [comment]
The implementation looks cool.
