### ISSUE TITLE
[ENHANCMENT] Properly align and style header on mobile screens

### ISSUE THREAD

**Issue by Jason-bolt** [Githubstreak/Githubstreak-frontend#27]
**Is your feature request related to a problem? Please describe.**
On mobile screens, the header does not look good.

**Describe the solution you'd like**
The header should be better formatted.

**Environment (please complete the following information):**
Mobile phone, Samsung S10+

**Would you be willing to submit a pull request?**
Yes

**Comment by KwameTech1** [comment]
Thanks for pointing the issue out, It has been fixed.
